/**
 * The world-level "what happened while you were away", as maths.
 *
 * Every assertion here is a claim the drawer makes about a tank the visitor was
 * not watching: how many days closed, whether a species is gone, whether a day's
 * commitment reached the chain. The interesting failures are the ones where the
 * arithmetic is right and the sentence is wrong — a window that no longer holds
 * the days being described, a book that arrived empty, a tank that was replaced
 * — so those are what this file spends its lines on rather than the happy path.
 *
 * The fixture is `harness.js`'s day book, written out by hand: `diffWorld` is
 * only honest if the server's `changes` list and the rows agree, and a fixture
 * generated by the code under test would agree with it no matter how both were
 * wrong.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { WORLD_KIND_ORDER, WORLD_SINCE_V, diffWorld, worldSeed } from '../src/worldsince.js';
import { census, censusRow } from './harness.js';

// A book the visitor saw is a *window*, so the payload helper takes the coverage
// start separately from the rows it happens to hold: a one-row book whose
// coverage starts at that row's day is a tank that has lived one day, and the
// trimming logic below would be reading a fiction. Every fixture that stands for
// "a deep book, stored small" says where its window began.
const payload = (rows, over = {}) => ({
  book: rows.length,
  coverage: rows.length
    ? { first: over.coverageFirst ?? rows[0].day, last: rows[rows.length - 1].day, days: rows.length }
    : null,
  rows,
  changes: [],
  ...over,
});

test('a seed records the edges of the book and the newest confirmation', () => {
  const s = worldSeed(census);
  assert.equal(s.v, WORLD_SINCE_V);
  assert.equal(s.lastDay, 4, 'the newest closed day, not the day the tank is living in');
  assert.equal(s.coverageFirst, 0);
  assert.equal(s.population, 6, 'the last row, including the species our archetype list has never heard of');
  assert.deepEqual(s.byArchetype, { APE: 2, WHALE: 2, ALGO: 1, CRAB: 1 });
  assert.equal(s.anchoredThrough, 4, 'day 4 has a txHash; day 3 is not in the book at all');
  // The key set, on purpose: every stored field is a field a later visit compares,
  // so a name added here without a reader in `diffWorld` fails this instead of
  // riding along in browsers unnoticed.
  assert.deepEqual(Object.keys(s).sort(), ['anchoredThrough', 'byArchetype', 'coverageFirst', 'lastDay', 'population', 'v']);

  const empty = worldSeed(payload([]));
  assert.equal(empty.lastDay, null, 'a book with no rows has no newest day, and does not invent one');
  assert.deepEqual(empty.byArchetype, {});
  assert.equal(empty.anchoredThrough, null);
  assert.equal(empty.coverageFirst, null);
  assert.equal(worldSeed(null).v, WORLD_SINCE_V, 'no payload is still a shape, just an empty one');
  assert.equal(worldSeed(undefined).lastDay, null);
});

test('a hash that is not a hash does not count as a confirmation', () => {
  // The server only ever writes `0x` plus 64 here, but the reader is a browser's
  // memory of an answer from an isolate that could have been an older build.
  const s = worldSeed(payload([censusRow(2, { APE: 1 }, 'cc60e690')]));
  assert.equal(s.anchoredThrough, null, 'a missing 0x prefix is not a confirmation');
  assert.equal(worldSeed(payload([censusRow(2, { APE: 1 }, 0x1234)])).anchoredThrough, null, 'a number is not either');
});

test('the first visit has nothing to compare, and so does a different shape', () => {
  const now = worldSeed(census);
  assert.equal(diffWorld(null, now, census.changes), null, 'no memory is not the same as a quiet spell');
  assert.equal(diffWorld(now, null, census.changes), null);
  assert.equal(diffWorld({ ...now, v: 99 }, now, census.changes), null, 'a stored baseline of another version is refused, not diffed field by field');
  assert.equal(diffWorld(now, { ...now, v: 99 }, census.changes), null);
});

test('a book that went backwards is refused rather than narrated', () => {
  // Days are written once and never rewritten, so a lower newest day means the
  // tank this memory belongs to is not the tank being looked at. Every item a
  // comparison would produce is a statement about a world that never existed.
  const prev = worldSeed(payload([censusRow(9, { APE: 3 })]));
  const next = worldSeed(payload([censusRow(2, { APE: 3 })]));
  assert.equal(diffWorld(prev, next, []), null);
});

test('one closed day says one closed day, with the numbers beside it', () => {
  const prev = worldSeed(payload([censusRow(0, { APE: 2 }), censusRow(3, { APE: 2, WHALE: 2, ALGO: 1 })]));
  const next = worldSeed(payload([
    censusRow(0, { APE: 2 }),
    censusRow(3, { APE: 2, WHALE: 2, ALGO: 1 }),
    censusRow(4, { APE: 2, WHALE: 2, ALGO: 1, CRAB: 1 }),
  ]));
  const items = diffWorld(prev, next, [{ day: 4, lost: [], gained: ['CRAB'] }]);
  assert.deepEqual(items.map((i) => i.kind), ['days', 'population', 'emerged', 'net']);
  const days = items.find((i) => i.kind === 'days');
  assert.equal(days.n, 1);
  assert.equal(days.from, 3);
  assert.equal(days.to, 4);
  assert.equal(days.partial, false, 'the window still holds the day being compared against');
  assert.deepEqual(items.find((i) => i.kind === 'emerged').species, ['CRAB']);
  // Population was 5 against 6, and neither row is missing its number.
  assert.deepEqual(items.find((i) => i.kind === 'population'), { kind: 'population', from: 5, to: 6, delta: 1 });
  assert.deepEqual(items.find((i) => i.kind === 'net').perSpecies, [{ species: 'CRAB', from: 0, to: 1 }]);
});

test('a same-day revisit says nothing, unless a confirmation arrived', () => {
  const prev = worldSeed(census);
  const next = worldSeed(payload(census.rows.map((r) => ({ ...r })), { changes: census.changes }));
  assert.deepEqual(diffWorld(prev, next, census.changes), [], 'memory, and nothing to report');

  // Day 4 was in the book unconfirmed at 13:00 and confirmed at 18:00. The visitor
  // missed the transaction, not the day, and the drawer must not claim a day
  // closed that they already saw.
  const before = { ...worldSeed(census), anchoredThrough: 0 };
  const withTx = worldSeed(payload(census.rows.map((r) => (r.day === 4 ? { ...r, txHash: '0x' + 'ee'.repeat(32) } : r))));
  const items = diffWorld(before, withTx, census.changes);
  assert.deepEqual(items, [{ kind: 'anchored', from: 0, to: 4 }],
    'the claim is the watermark, not a count: days 1 and 2 of that gap have no transaction to point at');

  // Somebody who has never seen a stamped row is not being told a delta from day
  // `null`, and a book whose window starts at day 210 has no day 0 to name.
  const firstStamp = diffWorld({ ...before, anchoredThrough: null }, withTx, census.changes);
  assert.deepEqual(firstStamp, [{ kind: 'anchored', from: null, to: 4 }]);
});

test('news is counted over the days between the two readings, not over the whole window', () => {
  // The server reports every change the fetched window holds, and its published
  // rule is that a species which vanished and came back inside that window is
  // reported as both (see the header of `censusEvents` in src/census.js). So the
  // claim this guards is the *window*: a visitor who saw day 4 is told about days
  // 5 and 6, and the emergence they already read is not repeated at them.
  const rows = [
    censusRow(4, { APE: 2, WHALE: 2, ALGO: 1, CRAB: 1 }),
    censusRow(5, { APE: 2, WHALE: 2, ALGO: 1 }),
    censusRow(6, { APE: 2, WHALE: 2, ALGO: 1, CRAB: 1 }),
  ];
  const prev = worldSeed(payload(rows.slice(0, 1), { coverageFirst: 0 }));
  const next = worldSeed(payload(rows));
  const changes = [
    { day: 4, lost: [], gained: ['CRAB'] },
    { day: 5, lost: ['CRAB'], gained: [] },
    { day: 6, lost: [], gained: ['CRAB'] },
  ];
  const items = diffWorld(prev, next, changes);
  assert.deepEqual(items.find((i) => i.kind === 'extinct').species, ['CRAB']);
  assert.deepEqual(items.find((i) => i.kind === 'emerged').species, ['CRAB'], 'lost and gained in the same span are two sentences, not zero');
  assert.equal(items.find((i) => i.kind === 'extinct').trimmed, false, 'the span is fully covered by rows in hand');
  assert.equal(items.find((i) => i.kind === 'days').n, 2, 'days 5 and 6 closed while the visitor was away');
  // The count went 6 → 5 → 6 across the span. `population` compares the two edges,
  // so it stays silent here — and that is not the dip being hidden: day 5's loss
  // is carried by the `extinct` item above, which comes from the server's
  // day-by-day list rather than from this file's arithmetic.
  assert.equal(items.some((i) => i.kind === 'population'), false, '6 against 6 is not a change of population');
});

test('a trimmed baseline is said out loud instead of being smoothed over', () => {
  // The visitor's memory is of day 200; the book now starts at day 210. The days
  // between them are not quiet, they are gone, and a count of the rows in hand
  // cannot tell the two apart.
  const prev = worldSeed(payload([censusRow(200, { APE: 5 })]));
  const next = worldSeed(payload([censusRow(210, { APE: 5 }), censusRow(211, { APE: 5 })]));
  const items = diffWorld(prev, next, []);
  const days = items.find((i) => i.kind === 'days');
  assert.equal(days.n, 11, 'the elapsed days are still eleven, trimmed or not');
  assert.equal(days.partial, true);
  assert.equal(days.trimmed, 10, 'ten of them have no rows left to describe');
  assert.equal(items.find((i) => i.kind === 'days').from, 200, 'the span still starts where the memory does');
});

test('one day below the floor is trimmed by one, and none by nothing', () => {
  // The edge the "no longer in the book" sentence stands or falls on: a memory
  // whose newest day *is* the oldest row in hand has lost nothing, and one day
  // lower has lost exactly one day. Getting these two wrong by one is the
  // difference between silence and a false alarm about the tank's own past.
  const floor = worldSeed(payload([censusRow(9, { APE: 2 })]));
  const onFloor = diffWorld(floor, worldSeed(payload([censusRow(9, { APE: 2 }), censusRow(10, { APE: 3 })])), []);
  assert.deepEqual(onFloor.find((i) => i.kind === 'days'), {
    kind: 'days', n: 1, from: 9, to: 10, partial: false, trimmed: 0,
  }, 'the day being compared against is still in the book');

  const lower = worldSeed(payload([censusRow(8, { APE: 2 })]));
  const trimmed = diffWorld(lower, worldSeed(payload([censusRow(9, { APE: 2 }), censusRow(10, { APE: 3 })])), []);
  assert.deepEqual(trimmed.find((i) => i.kind === 'days'), {
    kind: 'days', n: 2, from: 8, to: 10, partial: true, trimmed: 1,
  }, 'day 8 has no row any more, and that is one day, not two');
});

test('an empty changes list is not an error and cannot invent a species', () => {
  const prev = worldSeed(payload([censusRow(0, { APE: 2 }), censusRow(1, { APE: 2 })]));
  const next = worldSeed(payload([censusRow(0, { APE: 2 }), censusRow(1, { APE: 2 }), censusRow(2, { APE: 2, WHALE: 1 })]));
  const items = diffWorld(prev, next, null);
  assert.equal(items.some((i) => i.kind === 'emerged'), false, 'WHALE appeared between two rows, and the server did not say so');
  assert.deepEqual(items.map((i) => i.kind), ['days', 'population', 'net']);
});

test('a missing population is not a change of population', () => {
  const prev = { ...worldSeed(payload([censusRow(0, { APE: 2 }), censusRow(1, { APE: 2 })])), population: null };
  const next = worldSeed(payload([censusRow(0, { APE: 2 }), censusRow(1, { APE: 2 }), censusRow(2, { APE: 7 })]));
  const items = diffWorld(prev, next, []);
  assert.equal(items.some((i) => i.kind === 'population'), false);
  assert.equal(items.find((i) => i.kind === 'days').n, 1, 'the day still closed, and that is still true');
});

test('the net line ranks by the move, not by the alphabet', () => {
  // Three species get named and the rest are counted, so this order decides who is
  // named. A comparator that quietly degenerates to its own tiebreak ships
  // unnoticed but for this: the animal that doubled would lose its place to one
  // that drifted by a head, because its name starts earlier.
  const net = diffWorld(
    worldSeed(payload([censusRow(1, { ALPHA: 10, ZULU: 1 })])),
    worldSeed(payload([censusRow(1, { ALPHA: 10, ZULU: 1 }), censusRow(2, { ALPHA: 9, ZULU: 6 })])),
    [],
  ).find((i) => i.kind === 'net');
  assert.deepEqual(net.perSpecies.map((r) => r.species), ['ZULU', 'ALPHA'], 'five heads gained is not second place');

  const tie = diffWorld(
    worldSeed(payload([censusRow(1, { MIKE: 1, DAN: 1 })])),
    worldSeed(payload([censusRow(1, { MIKE: 1, DAN: 1 }), censusRow(2, { MIKE: 2, DAN: 2 })])),
    [],
  ).find((i) => i.kind === 'net');
  assert.deepEqual(
    tie.perSpecies.map((r) => r.species),
    ['DAN', 'MIKE'],
    'an equal move is broken by name, not by whichever key the object happened to list first',
  );
});

test('the order is the drawer\'s, not the arithmetic\'s', () => {
  const prev = worldSeed(payload([censusRow(0, { APE: 2, INSIDER: 1 }), censusRow(1, { APE: 2, INSIDER: 1 })]));
  const next = worldSeed(payload([
    censusRow(0, { APE: 2, INSIDER: 1 }),
    censusRow(1, { APE: 2, INSIDER: 1 }),
    censusRow(2, { APE: 2, CRAB: 1 }),
    censusRow(3, { APE: 3, CRAB: 1 }),
  ]));
  const items = diffWorld(prev, next, [
    { day: 2, lost: ['INSIDER'], gained: [] },
    { day: 3, lost: [], gained: ['CRAB'] },
  ]);
  assert.deepEqual(items.map((i) => i.kind), WORLD_KIND_ORDER.filter((k) => items.some((i) => i.kind === k)));
  assert.equal(items[0].kind, 'extinct', 'bad news is not last because its object key was');
  assert.deepEqual(items.map((i) => i.kind), ['extinct', 'days', 'population', 'emerged', 'net']);
});
