export { Rng } from './prng.js';
export {
  INPUT_SIZE,
  HIDDEN_SIZE,
  OUTPUT_SIZE,
  ARCHETYPES,
  ARCHETYPE_LIST,
  GENE_TRAITS,
  archetypeOf,
  creatureName,
  randomGenome,
  cloneGenome,
  mutateGenome,
  mutateTrait,
  forward,
  genomeFingerprint,
  personaOf,
  steerArchetype,
} from './genome.js';
export type { GeneTrait, Genome, BrainOutput, Archetype, ArchetypeTraits } from './genome.js';
export { DEFAULT_CONFIG } from './types.js';
export type { WorldConfig } from './types.js';
export {
  createWorld,
  tick,
  applyIntervention,
  idsInZone,
  effectiveSpawnRate,
  txLanding,
  toJSON,
  fromJSON,
  STATS_LOG_CAP,
  STATS_LOG_TRIM,
  DO_VALUE_LIMIT,
  SNAPSHOT_BUDGET,
  WHALE_BOOM_SIZE,
  WISH_METEOR_SIZE,
  WISH_PELLETS,
  LEGENDARY_GENERATION,
  LEGENDARY_KILLS,
  isLegendary,
  displayName,
  findCreature,
  isHungry,
  dominantTax,
} from './world.js';
export type {
  Creature,
  Food,
  Intervention,
  InterventionResult,
  Obituary,
  TimedEffect,
  CullType,
  CullRecord,
  SimEvent,
  Senses,
  TickStats,
  TxMeteor,
  World,
} from './world.js';
